name: build-review-app
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - '*'
      - '!master'

jobs:
  connect-vpn-build-qa:
    name: install ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Extract branch name
      shell: bash
      run: echo "${GITHUB_REF}"
      id: extract_branch

    - name: Step that prints name of pull request's base branch
      run: echo "Pull request's base branch is. ${BASE_BRANCH}" && echo "Pull request's compare branch is. ${COMPARE_BRANCH}" && echo "$GITHUB_CONTEXT"
      env:
        BASE_BRANCH: ${{ github.base_ref }}
        COMPARE_BRANCH: ${{ github.compare_ref }}
        GITHUB_CONTEXT: ${{ toJson(github) }}