name: build-qa
on:
  push:
    branches: 
      - dev

jobs:
  connect-vpn-build-qa:
    name: install ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install Open VPN
      run: sudo apt install openvpn -y && sudo apt install expect

    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '127.0.0.1'
        FILE_OVPN: '.github/vpn/config.ovpn'
      env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
          
    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }} && expect -c 'spawn ssh -o "StrictHostKeyChecking no" adminmo@$10.153.144.218 "ls -lha"; expect "password:"; send "RaymundoSalser07?\r"; interact;'

    - name: build action
      run: ls -lha && ifconfig -a

    - name: kill vpn
      if: always()
      run: sudo killall openvpn
