name: test-vpn
on:
  push:
    branches: 
      - dev

jobs:
  test-vpn:
    name: test-vpn
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install Open VPN
      run: sudo apt-get install openvpn

    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '127.0.0.1'
        FILE_OVPN: '.github/vpn/config.ovpn'

    - name: Check Connect VPN
      run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      
    - name: kill vpn
      if: always()
      run: sudo killall openvpn
